# Generated by Django 2.1.15 on 2019-12-28 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'login_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RealName',
            fields=[
                ('rnid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=4)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=11)),
                ('idnumber', models.CharField(max_length=18)),
                ('idfront', models.ImageField(upload_to='id_img/front/')),
                ('idbehind', models.ImageField(upload_to='id_img/behind/')),
                ('date', models.DateTimeField()),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='XXX.LoginUser')),
                ('account', models.CharField(blank=True, max_length=20, null=True)),
                ('head_img', models.ImageField(upload_to='head_img/')),
                ('credit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_info',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='realname',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XXX.LoginUser'),
        ),
    ]
