# Generated by Django 2.1.15 on 2019-12-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XXX', '0002_auto_20191228_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='head_img',
            field=models.ImageField(default='/static/images/1.jpg', null=True, upload_to='head_img/'),
        ),
    ]
