# Generated by Django 2.1.15 on 2019-12-28 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('XXX', '0004_auto_20191228_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHome',
            fields=[
                ('hid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('type', models.CharField(max_length=8)),
                ('prove', models.ImageField(upload_to='home_prove/')),
                ('date', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XXX.LoginUser')),
            ],
        ),
        migrations.AlterModelOptions(
            name='realname',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='realname',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='realname',
            table='real_name',
        ),
    ]
