# Generated by Django 2.1.15 on 2019-12-28 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XXX', '0005_auto_20191228_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userhome',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='userhome',
            table='user_home',
        ),
    ]
