# Generated by Django 2.1.15 on 2019-12-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XXX', '0006_auto_20191228_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhome',
            name='date',
        ),
        migrations.AddField(
            model_name='userhome',
            name='prove_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
