# Generated by Django 2.1.15 on 2019-12-29 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('XXX', '0007_auto_20191228_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPublish',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('home_name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('situation_desc', models.CharField(max_length=200)),
                ('facilities', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='home_image/')),
                ('status', models.IntegerField(default=0)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XXX.LoginUser')),
            ],
            options={
                'db_table': 'user_publish',
                'managed': True,
            },
        ),
    ]
