# Generated by Django 2.1.15 on 2019-12-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XXX', '0008_userpublish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpublish',
            name='facilities',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpublish',
            name='situation_desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
