# Generated by Django 2.1.15 on 2019-12-29 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('XXX', '0010_auto_20191229_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='home_img/')),
            ],
            options={
                'db_table': 'home_image',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='userpublish',
            name='images',
        ),
        migrations.AddField(
            model_name='userpublish',
            name='image_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='homeimage',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='XXX.UserPublish'),
        ),
        migrations.AlterUniqueTogether(
            name='homeimage',
            unique_together={('pid', 'image_id')},
        ),
    ]
