# Generated by Django 2.1.15 on 2019-12-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XXX', '0011_auto_20191229_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpublish',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
