# Generated by Django 2.1.15 on 2019-12-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XXX', '0013_auto_20191229_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhome',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userpublish',
            name='home_name',
            field=models.CharField(max_length=20),
        ),
    ]
