# Generated by Django 2.1.15 on 2019-12-29 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('XXX', '0014_auto_20191229_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhome',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='userpublish',
            name='home_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='XXX.UserHome', to_field='name'),
        ),
    ]
