# Generated by Django 2.1.15 on 2019-12-29 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('XXX', '0015_auto_20191229_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpublish',
            name='home_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='XXX.UserHome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userhome',
            name='hid',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userhome',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userpublish',
            name='home_name',
            field=models.CharField(max_length=20),
        ),
    ]
