# Generated by Django 2.1.15 on 2019-12-29 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('XXX', '0016_auto_20191229_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpublish',
            name='home_id',
        ),
    ]
