# Generated by Django 2.1.15 on 2019-12-29 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('XXX', '0017_remove_userpublish_home_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpublish',
            name='hid',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='XXX.UserHome'),
        ),
    ]
