# Generated by Django 2.1.15 on 2019-12-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XXX', '0019_remove_userpublish_hid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhome',
            name='hid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
