# Generated by Django 2.1.15 on 2019-12-30 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('XXX', '0020_auto_20191229_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImg',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='轮播图片')),
                ('status', models.IntegerField(verbose_name='是否显示')),
            ],
            options={
                'verbose_name': '首页轮播图',
                'verbose_name_plural': '首页轮播图',
                'db_table': 'banner_image',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='homeimage',
            options={'managed': True, 'verbose_name': '住屋照片表', 'verbose_name_plural': '住屋照片表'},
        ),
        migrations.AlterModelOptions(
            name='loginuser',
            options={'managed': True, 'verbose_name': '登陆用户表', 'verbose_name_plural': '登陆用户表'},
        ),
        migrations.AlterModelOptions(
            name='realname',
            options={'managed': True, 'verbose_name': '用户实名认证表', 'verbose_name_plural': '用户实名认证表'},
        ),
        migrations.AlterModelOptions(
            name='userhome',
            options={'managed': True, 'verbose_name': '用户住屋表', 'verbose_name_plural': '用户住屋表'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': True, 'verbose_name': '用户基本信息表', 'verbose_name_plural': '用户基本信息表'},
        ),
        migrations.AlterModelOptions(
            name='userpublish',
            options={'managed': True, 'verbose_name': '用户发布房屋表', 'verbose_name_plural': '用户发布房屋表'},
        ),
        migrations.AlterField(
            model_name='homeimage',
            name='image',
            field=models.ImageField(upload_to='home_img/', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='homeimage',
            name='image_id',
            field=models.IntegerField(verbose_name='照片ID'),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='email',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='pwd',
            field=models.CharField(max_length=20, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='realname',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='realname',
            name='date',
            field=models.DateTimeField(verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='realname',
            name='idbehind',
            field=models.ImageField(upload_to='id_img/behind/', verbose_name='身份证背面照片'),
        ),
        migrations.AlterField(
            model_name='realname',
            name='idfront',
            field=models.ImageField(upload_to='id_img/front/', verbose_name='身份证正面照片'),
        ),
        migrations.AlterField(
            model_name='realname',
            name='idnumber',
            field=models.CharField(max_length=18, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='realname',
            name='name',
            field=models.CharField(max_length=10, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='realname',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='realname',
            name='rnid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='realname',
            name='sex',
            field=models.CharField(max_length=4, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='realname',
            name='status',
            field=models.IntegerField(default=0, verbose_name='是否通过认证'),
        ),
        migrations.AlterField(
            model_name='userhome',
            name='area',
            field=models.IntegerField(verbose_name='住屋面积/平方米'),
        ),
        migrations.AlterField(
            model_name='userhome',
            name='hid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='userhome',
            name='location',
            field=models.CharField(max_length=50, verbose_name='住屋详细地址'),
        ),
        migrations.AlterField(
            model_name='userhome',
            name='name',
            field=models.CharField(max_length=20, verbose_name='住屋名称'),
        ),
        migrations.AlterField(
            model_name='userhome',
            name='prove',
            field=models.ImageField(upload_to='home_prove/', verbose_name='住屋证明照片'),
        ),
        migrations.AlterField(
            model_name='userhome',
            name='prove_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='通过认证时间'),
        ),
        migrations.AlterField(
            model_name='userhome',
            name='status',
            field=models.IntegerField(default=0, verbose_name='是否通过认证'),
        ),
        migrations.AlterField(
            model_name='userhome',
            name='type',
            field=models.CharField(max_length=8, verbose_name='住屋类型'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='account',
            field=models.CharField(default='一只小XX', max_length=20, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='credit',
            field=models.IntegerField(default=100, verbose_name='信誉值'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='XXX.LoginUser', verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='head_img',
            field=models.ImageField(default='/static/images/1.jpg', upload_to='head_img/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userpublish',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='发布日期'),
        ),
        migrations.AlterField(
            model_name='userpublish',
            name='end_date',
            field=models.DateField(verbose_name='闲屋结束时间'),
        ),
        migrations.AlterField(
            model_name='userpublish',
            name='facilities',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='住房家具设施'),
        ),
        migrations.AlterField(
            model_name='userpublish',
            name='home_name',
            field=models.CharField(max_length=20, verbose_name='房屋名称'),
        ),
        migrations.AlterField(
            model_name='userpublish',
            name='image_num',
            field=models.IntegerField(default=0, verbose_name='住房照片数量'),
        ),
        migrations.AlterField(
            model_name='userpublish',
            name='pid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='userpublish',
            name='price',
            field=models.IntegerField(verbose_name='价格/元每晚'),
        ),
        migrations.AlterField(
            model_name='userpublish',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='房屋准则'),
        ),
        migrations.AlterField(
            model_name='userpublish',
            name='situation_desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='住房附近交通情况'),
        ),
        migrations.AlterField(
            model_name='userpublish',
            name='start_date',
            field=models.DateField(verbose_name='闲屋开始时间'),
        ),
        migrations.AlterField(
            model_name='userpublish',
            name='status',
            field=models.IntegerField(default=0, verbose_name='发布是否过期'),
        ),
        migrations.AlterField(
            model_name='userpublish',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
    ]
