# Generated by Django 2.1.15 on 2019-12-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XXX', '0021_auto_20191230_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='轮播图片')),
                ('text_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(verbose_name='是否显示')),
            ],
            options={
                'verbose_name': '首页轮播图',
                'verbose_name_plural': '首页轮播图',
                'db_table': 'banner_image',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='BannerImg',
        ),
    ]
